apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: trend-app
  template:
    metadata:
      labels:
         app: trend-app
    spec:
       containers:
       - name: trend-container
         image: crazy1/trend-app:IMAGE_TAG    #jenkins will replace IMAGE_TAG
         ports:
         - containerPort: 80    
